application: hypno-go-spec
version: 1
runtime: go
api_version: go1

handlers:
# Real App Resources
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /hypnotic_go_spec.dart.js
  static_files: static/hypnotic_go_spec.dart.js
  upload: static/hypnotic_go_spec.dart.js
- url: /hypnotic_go_spec.dart
  static_files: static/hypnotic_go_spec.dart
  upload: static/hypnotic_go_spec.dart
- url: /hypnotic_go_spec.dart.js.map
  static_files: static/hypnotic_go_spec.dart.js.map
  upload: static/hypnotic_go_spec.dart.js.map
- url: /dart.js
  static_files: static/dart.js
  upload: static/dart.js
# Demo1 Resources
- url: /demo1
  static_files: demo1/index.html
  upload: demo1/index.html
- url: /demo1/hypnotic_go_spec.dart.js
  static_files: demo1/hypnotic_go_spec.dart.js
  upload: demo1/hypnotic_go_spec.dart.js
- url: /demo1/hypnotic_go_spec.dart
  static_files: demo1/hypnotic_go_spec.dart
  upload: demo1/hypnotic_go_spec.dart
- url: /demo1/hypnotic_go_spec.dart.js.map
  static_files: demo1/hypnotic_go_spec.dart.js.map
  upload: demo1/hypnotic_go_spec.dart.js.map
# Demo2 Resources
- url: /demo2
  static_files: demo2/index.html
  upload: demo2/index.html
- url: /demo2/hypnotic_go_spec.dart.js
  static_files: demo2/hypnotic_go_spec.dart.js
  upload: demo2/hypnotic_go_spec.dart.js
- url: /demo2/hypnotic_go_spec.dart
  static_files: demo2/hypnotic_go_spec.dart
  upload: demo2/hypnotic_go_spec.dart
- url: /demo2/hypnotic_go_spec.dart.js.map
  static_files: demo2/hypnotic_go_spec.dart.js.map
  upload: demo2/hypnotic_go_spec.dart.js.map
# Demo3 Resources
- url: /demo3
  static_files: demo3/index.html
  upload: demo3/index.html
- url: /demo3/hypnotic_go_spec.dart.js
  static_files: demo3/hypnotic_go_spec.dart.js
  upload: demo3/hypnotic_go_spec.dart.js
- url: /demo3/hypnotic_go_spec.dart
  static_files: demo3/hypnotic_go_spec.dart
  upload: demo3/hypnotic_go_spec.dart
- url: /demo3/hypnotic_go_spec.dart.js.map
  static_files: demo3/hypnotic_go_spec.dart.js.map
  upload: demo3/hypnotic_go_spec.dart.js.map
